#!/bin/bash

FOUND=0
while [ "$PWD" != "/" ];  do
  for i in *; do
    if [[ $i =~ $1 ]] && [ -f $i ]; then
      echo "`pwd`/$i"
      FOUND=1
    fi
  done
  cd ..
done

if [ $FOUND -eq 1 ]; then exit 0; fi
exit 1

